repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run isort .
        language: system
        types: [python]
        pass_filenames: false
        stages: [commit]

      - id: black
        name: black
        entry: poetry run black .
        language: system
        types: [python]
        pass_filenames: false
        stages: [commit]

      - id: flake8
        name: flake8
        entry: poetry run flake8 .
        language: system
        types: [python]
        pass_filenames: false
        stages: [commit]

      - id: mypy
        name: mypy
        entry: poetry run mypy .
        language: system
        types: [python]
        pass_filenames: false
        stages: [commit]

      - id: pytest
        name: pytest
        entry: poetry run pytest
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
        stages: [push]